"""empty message

Revision ID: 3f68c90d87f2
Revises: 4156400f3989
Create Date: 2018-01-28 13:29:39.803289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f68c90d87f2'
down_revision = '4156400f3989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'score',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    op.alter_column('user', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('user', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
