"""empty message

Revision ID: 4156400f3989
Revises: f024b7c6c5bc
Create Date: 2018-01-28 13:13:54.928774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4156400f3989'
down_revision = 'f024b7c6c5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'score',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    op.alter_column('user', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('user', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
