"""empty message

Revision ID: 5fa773c8f78b
Revises: f69b6fb36e32
Create Date: 2018-01-28 13:34:10.974462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa773c8f78b'
down_revision = 'f69b6fb36e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('user', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    op.alter_column('user', 'profile_picture',
               existing_type=sa.String(length=80),
               type_=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'score',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text("'5'::real"))
    op.alter_column('user', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('user', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
