"""empty message

Revision ID: c70479431c49
Revises: c3128ea4b313
Create Date: 2018-01-28 09:15:25.654073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70479431c49'
down_revision = 'c3128ea4b313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lat', sa.Float(precision=10), nullable=True))
    op.add_column('user', sa.Column('lng', sa.Float(precision=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lng')
    op.drop_column('user', 'lat')
    # ### end Alembic commands ###
